# Generated by Copilot assistant Feb 23 2026

from django.db import migrations, models
import django.utils.timezone


def create_default_courses(apps, schema_editor):
    Course = apps.get_model('students', 'Course')
    for name, code in [('English', 'ENG101'), ('Maths', 'MATH101'), ('Physics', 'PHY101')]:
        Course.objects.get_or_create(code=code, defaults={'name': name})


def set_expiry(apps, schema_editor):
    AttendanceSession = apps.get_model('students', 'AttendanceSession')
    now = django.utils.timezone.now()
    for sess in AttendanceSession.objects.all():
        if not sess.expires_at:
            sess.expires_at = now + django.utils.timezone.timedelta(minutes=2)
            sess.save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='expires_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.RunPython(create_default_courses, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_expiry, reverse_code=migrations.RunPython.noop),
    ]
