# Generated by Copilot assistant Feb 23 2026

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_add_expires_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, null=True, max_digits=9, decimal_places=6),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, null=True, max_digits=9, decimal_places=6),
        ),
    ]
